version: '3.4'

services:
  testedeltaapi:
    image: testedeltaapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DATABASE_URL: 'postgres://user:password@db:54320/db'
      PORT: '3000'
      NODE_ENV: 'development'
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      - production-network
  db:
    image: postgres:10.4
    ports:
      - '54320:54320'
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'db'
      DB_HOST: 'localhost'
    networks:
      - production-network
networks:
  production-network:
    driver: bridge
    external: true
